# -*- coding: utf-8 -*-
"""Fuel Price Optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15J8JwmtrvifrBNhrx7OXIa2mhISAsTQr
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
from sklearn.metrics import (accuracy_score, f1_score, roc_auc_score,mean_squared_error, mean_absolute_error, r2_score)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler,LabelEncoder
from xgboost import XGBRFRegressor,XGBRegressor

df = pd.read_csv('/content/oil_retail_history.csv')

df.head(10)

df.info()

df.describe()

df.isnull().sum()

df['price']>=df['cost'].all()

df['volume']>0

df['date'] = pd.to_datetime(df['date'])

plt.figure(figsize = (10,6))
plt.plot(df['comp1_price'],color = 'red')
plt.plot(df['price'],color = 'black')

plt.figure(figsize=(30,8))

plt.plot(df['date'], df['comp1_price'], color='red', label='Competitor 1 Price')
plt.plot(df['date'], df['comp2_price'], color='blue', label='Competitor 2 Price')
plt.plot(df['date'], df['comp3_price'], color='yellow', label='Competitor 3 Price')
plt.plot(df['date'], df['price'], color='black', label='Our Price',marker = '*')
plt.xlabel('Date')
plt.ylabel('Price')
plt.title('Our Price vs Competitor 1 Price Over Time')
plt.legend()
plt.show()

plt.figure(figsize=(25,8))

plt.plot(df['date'], df['price'], color='black', linewidth=2, label='Our Price')
plt.plot(df['date'], df['comp1_price'], linestyle='--', label='Comp 1')
plt.plot(df['date'], df['comp2_price'], linestyle='--', label='Comp 2')
plt.plot(df['date'], df['comp3_price'], linestyle='--', label='Comp 3')
plt.xlabel('Date')
plt.ylabel('Price')
plt.title('Our Price vs Competitor Prices')
plt.legend()
plt.show()

df['avg_comp_price'] = df[['comp1_price','comp2_price','comp3_price']].mean(axis=1)
df['price_diff'] = df['price'] - df['avg_comp_price']
plt.figure(figsize=(8,6))
plt.scatter(
    df['price_diff'],
    df['volume'],
    color='blue',
    alpha=0.5
)

plt.axvline(0, color='red', linestyle='--', label='Parity with Competitors')

plt.xlabel('Price Difference (Our − Competitors)')
plt.ylabel('Volume Sold')
plt.title('Price Difference vs Volume')
plt.legend()
plt.show()

df = df.sort_values("date").reset_index(drop=True)

df['avg_comp_price'] = df[['comp1_price','comp2_price','comp3_price']].mean(axis=1)
df['price_diff'] = df['price'] - df['avg_comp_price']

df['volume_lag_1'] = df['volume'].shift(1)

df['volume_roll_7'] = df['volume'].rolling(7).mean()

df = df.dropna().reset_index(drop=True)

X = df[[
    'price',
    'cost',
    'comp1_price',
    'comp2_price',
    'comp3_price',
    'price_diff',
    'volume_lag_1',
    'volume_roll_7'
]]
y = df['volume']

X_train = X.iloc[:-60]
X_test  = X.iloc[-60:]

y_train = y.iloc[:-60]
y_test  = y.iloc[-60:]

baseline_pred = X_test['volume_roll_7']
baseline_r2 = r2_score(y_test, baseline_pred)
print("Baseline R2:", baseline_r2)

rf_model = RandomForestRegressor(
    n_estimators=200,
    max_depth=8,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

mse = mean_squared_error(y_test, rf_pred)
r2 = r2_score(y_test, rf_pred)

print("RF MSE:", mse)
print("RF R2:", r2)

"""XGBoost"""

xgb_model = XGBRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb_model.fit(X_train, y_train)

xgb_pred = xgb_model.predict(X_test)

print("XGB R2:", r2_score(y_test, xgb_pred))

importance = pd.Series(
    rf_model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print(importance)

import json

last_row = df.iloc[-1]

today_data = {
    "date": str(last_row["date"].date()),
    "last_price": float(last_row["price"]),
    "cost": float(last_row["cost"]),
    "comp1_price": float(last_row["comp1_price"]),
    "comp2_price": float(last_row["comp2_price"]),
    "comp3_price": float(last_row["comp3_price"])
}

with open("data/today.json", "w") as f:
    json.dump(today_data, f, indent=4)

import json

with open("data/today.json") as f:
    today = json.load(f)

import pandas as pd

def build_today_features(today, history_df):
    avg_comp_price = (
        today["comp1_price"] +
        today["comp2_price"] +
        today["comp3_price"]
    ) / 3

    price_diff = today["last_price"] - avg_comp_price

    volume_lag_1 = history_df.iloc[-1]["volume"]
    volume_roll_7 = history_df.iloc[-7:]["volume"].mean()
    dow = pd.to_datetime(today["date"]).dayofweek

    X_today = pd.DataFrame([{
        "price": today["last_price"],   # will be replaced during simulation
        "cost": today["cost"],
        "comp1_price": today["comp1_price"],
        "comp2_price": today["comp2_price"],
        "comp3_price": today["comp3_price"],
        "price_diff": price_diff,
        "volume_lag_1": volume_lag_1,
        "volume_roll_7": volume_roll_7,
        "dow": dow
    }])

    return X_today

from datetime import datetime, timedelta

def update_daily_json(prev_json, new_cost, comp_prices):
    new_date = (
        datetime.strptime(prev_json["date"], "%Y-%m-%d")
        + timedelta(days=1)
    ).strftime("%Y-%m-%d")

    return {
        "date": new_date,
        "last_price": prev_json["last_price"],
        "cost": new_cost,
        "comp1_price": comp_prices[0],
        "comp2_price": comp_prices[1],
        "comp3_price": comp_prices[2]
    }

